### ISSUE TITLE
@SerializedName annotation

### ISSUE THREAD

**Issue by isfaaghyth** [andriiginting/news-app#1]
Hi, Andri Ginting!

My name is Muh Isfhani Ghiath, I'm a beginner Android developer. I have a suggestion for the Model structure on this repository, in these model:
- https://github.com/andriiginting/news-app/blob/master/app/src/main/java/com/example/andriiginting/news/model/source/SourceResponse.kt
- https://github.com/andriiginting/news-app/blob/master/app/src/main/java/com/example/andriiginting/news/model/source/Sources.kt

maybe you shouldn't still use @SerializedName annotation anymore (in the case, the variable name matches the input name). There are instances where you may want to name a variable something other than the input, and that is where you will need the annotation to help gson with the mapping.

**Comment by andriiginting** [comment]
Hi @isfaaghyth thank you for your suggestion, i will check it

**Comment by isfaaghyth** [comment]
izin fork ya beb, izin berguru di akun github mu 😄
